apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}
  labels:
    app: {{APP_NAME}}
spec:
  type: LoadBalancer
  clusterIP: None
  selector:
    app: {{APP_NAME}}
  ports:
  - port: 80
    name: http
    protocol: TCP
  - port: 2004
    name: pickle
    protocol: TCP
